// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestfulDEMO.API.Data;

#nullable disable

namespace RestfulDEMO.API.Migrations
{
    [DbContext(typeof(RestfulDbContextA))]
    [Migration("20240218123242_Inital Migration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestfulDEMO.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c66e04fd-ba85-423f-8314-2cae09983a59"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("58dfb073-0e35-4b40-ada5-efd3b36974eb"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("7b0c6301-0a03-4e1b-9021-8419ab0ef7d4"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("RestfulDEMO.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e4e46541-1ce3-4ffe-8f89-f07f0259450f"),
                            Code = "BRG",
                            Name = "Bergen",
                            RegionImageUrl = "http/bergen/picture"
                        },
                        new
                        {
                            Id = new Guid("4c55f1bf-2af7-4463-8b55-e991e7377c4f"),
                            Code = "OSL",
                            Name = "Oslo",
                            RegionImageUrl = "http/oslo/picture"
                        },
                        new
                        {
                            Id = new Guid("8671f7ab-9c94-44ba-bdd4-b3d9e0dc4261"),
                            Code = "STV",
                            Name = "Stavanger",
                            RegionImageUrl = "http/stavanger/picture"
                        });
                });

            modelBuilder.Entity("RestfulDEMO.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("RestfulDEMO.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("RestfulDEMO.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestfulDEMO.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
